
package sistemadepositosagua;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Miguel
 */
public class SistemaDepositosAgua extends javax.swing.JFrame {

    private SistemaAgua sistema;
    private Deposito depoA;
    private Deposito depoB;
    private Deposito depoC;
    private int aguaTraspaso;
    private int trasAgua;

    /**
     * Creates new form DepositoAguaSwing
     */
    public SistemaDepositosAgua() {
        this.sistema = new SistemaAgua();
        this.sistema.addDeposito(depoA = new Deposito("DEPÓSITO-A", 100));
        this.sistema.addDeposito(depoB = new Deposito("DEPÓSITO-B", 100));
        this.sistema.addDeposito(depoC = new Deposito("DEPÓSITO-C", 100));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SistemaPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTraspasar = new javax.swing.JLabel();
        labelTrasEmisor = new javax.swing.JLabel();
        comboTrasEmisor = new javax.swing.JComboBox<>();
        labelTrasCantidad = new javax.swing.JLabel();
        labelTrasReceptor = new javax.swing.JLabel();
        comboTrasReceptor = new javax.swing.JComboBox<>();
        butTrasConfirmar = new javax.swing.JButton();
        butTras25 = new javax.swing.JButton();
        butTras40 = new javax.swing.JButton();
        butTras70 = new javax.swing.JButton();
        labelTest = new java.awt.Label();
        panelA = new javax.swing.JPanel();
        labACantidad = new javax.swing.JLabel();
        botAAñadir = new javax.swing.JButton();
        botAQuitar = new javax.swing.JButton();
        spinnerAAñadir = new javax.swing.JSpinner();
        labelAAcción = new javax.swing.JLabel();
        spinnerAQuitar = new javax.swing.JSpinner();
        labelDepositoA = new javax.swing.JLabel();
        labAAñadir = new javax.swing.JLabel();
        labAQuitar = new javax.swing.JLabel();
        labelACapacidad = new javax.swing.JLabel();
        labAUso = new javax.swing.JLabel();
        panelA1 = new javax.swing.JPanel();
        labBCantidad = new javax.swing.JLabel();
        botBAñadir = new javax.swing.JButton();
        botBQuitar = new javax.swing.JButton();
        spinnerBAñadir = new javax.swing.JSpinner();
        labelBAcción = new javax.swing.JLabel();
        spinnerBQuitar = new javax.swing.JSpinner();
        labelDepositoB = new javax.swing.JLabel();
        labBAñadir = new javax.swing.JLabel();
        labBQuitar = new javax.swing.JLabel();
        labelBCapacidad = new javax.swing.JLabel();
        labBUso = new javax.swing.JLabel();
        panelA2 = new javax.swing.JPanel();
        labCCantidad = new javax.swing.JLabel();
        botCAñadir = new javax.swing.JButton();
        botCQuitar = new javax.swing.JButton();
        spinnerCAñadir = new javax.swing.JSpinner();
        labelCAcción = new javax.swing.JLabel();
        spinnerCQuitar = new javax.swing.JSpinner();
        labelDepositoC = new javax.swing.JLabel();
        labCAñadir = new javax.swing.JLabel();
        labCQuitar = new javax.swing.JLabel();
        labelCCapacidad = new javax.swing.JLabel();
        labCUso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        labelTraspasar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTraspasar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTraspasar.setText("Traspasar agua");

        labelTrasEmisor.setText("Depósito emisor");

        comboTrasEmisor.addItem(depoA);
        comboTrasEmisor.addItem(depoB);
        comboTrasEmisor.addItem(depoC);
        comboTrasEmisor.setRenderer(new ListCellRender());
        comboTrasEmisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTrasEmisorActionPerformed(evt);
            }
        });

        labelTrasCantidad.setText("Cantidad");

        labelTrasReceptor.setText("Depósito receptor");

        comboTrasReceptor.addItem(depoA);
        comboTrasReceptor.addItem(depoB);
        comboTrasReceptor.addItem(depoC);
        comboTrasReceptor.setRenderer(new ListCellRender());
        comboTrasReceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTrasReceptorActionPerformed(evt);
            }
        });

        butTrasConfirmar.setText("Confirmar");
        butTrasConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTrasConfirmarActionPerformed(evt);
            }
        });

        butTras25.setText("25");
        butTras25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTras25ActionPerformed(evt);
            }
        });

        butTras40.setText("40");
        butTras40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTras40ActionPerformed(evt);
            }
        });

        butTras70.setText("70");
        butTras70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTras70ActionPerformed(evt);
            }
        });

        labelTest.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTraspasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butTrasConfirmar)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTrasEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(labelTrasEmisor)
                        .addGap(9, 9, 9))
                    .addComponent(comboTrasReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTrasReceptor))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(labelTrasCantidad))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(butTras25, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butTras40, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butTras70, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labelTraspasar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTrasEmisor)
                .addGap(18, 18, 18)
                .addComponent(comboTrasEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTrasReceptor)
                .addGap(18, 18, 18)
                .addComponent(comboTrasReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTrasCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butTras25)
                    .addComponent(butTras40)
                    .addComponent(butTras70))
                .addGap(67, 67, 67)
                .addComponent(butTrasConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        panelA.setBackground(new java.awt.Color(153, 153, 153));

        labACantidad.setText("Cantidad");

        botAAñadir.setText("Añadir");
        botAAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAAñadirActionPerformed(evt);
            }
        });

        botAQuitar.setText("Quitar");
        botAQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAQuitarActionPerformed(evt);
            }
        });

        spinnerAAñadir.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        labelAAcción.setText("Acción");

        spinnerAQuitar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        labelDepositoA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDepositoA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepositoA.setText("DEPÓSITO-A");

        labAAñadir.setText("AÑADIR");

        labAQuitar.setText("QUITAR");

        labelACapacidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelACapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelACapacidad.setText(depoA.toString());

        labAUso.setText("AGUA/CAPACIDAD");

        javax.swing.GroupLayout panelALayout = new javax.swing.GroupLayout(panelA);
        panelA.setLayout(panelALayout);
        panelALayout.setHorizontalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDepositoA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelALayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labACantidad)
                    .addComponent(labelAAcción))
                .addGap(18, 18, 18)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botAAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerAAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botAQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerAQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelACapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelALayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(labAAñadir)
                .addGap(52, 52, 52)
                .addComponent(labAQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(labAUso)
                .addGap(59, 59, 59))
        );
        panelALayout.setVerticalGroup(
            panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelALayout.createSequentialGroup()
                .addComponent(labelDepositoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labAAñadir)
                        .addComponent(labAQuitar))
                    .addComponent(labAUso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelALayout.createSequentialGroup()
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerAAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labACantidad)
                            .addComponent(spinnerAQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botAAñadir)
                            .addComponent(botAQuitar)
                            .addComponent(labelAAcción))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelALayout.createSequentialGroup()
                        .addComponent(labelACapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        panelA1.setBackground(new java.awt.Color(153, 153, 153));

        labBCantidad.setText("Cantidad");

        botBAñadir.setText("Añadir");
        botBAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBAñadirActionPerformed(evt);
            }
        });

        botBQuitar.setText("Quitar");
        botBQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBQuitarActionPerformed(evt);
            }
        });

        spinnerBAñadir.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        labelBAcción.setText("Acción");

        spinnerBQuitar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        labelDepositoB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDepositoB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepositoB.setText("DEPÓSITO-B");

        labBAñadir.setText("AÑADIR");

        labBQuitar.setText("QUITAR");

        labelBCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelBCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBCapacidad.setText(depoB.toString());

        labBUso.setText("AGUA/CAPACIDAD");

        javax.swing.GroupLayout panelA1Layout = new javax.swing.GroupLayout(panelA1);
        panelA1.setLayout(panelA1Layout);
        panelA1Layout.setHorizontalGroup(
            panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDepositoB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelA1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labBCantidad)
                    .addComponent(labelBAcción))
                .addGap(18, 18, 18)
                .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botBAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerBAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botBQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerBQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelBCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelA1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(labBAñadir)
                .addGap(52, 52, 52)
                .addComponent(labBQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(labBUso)
                .addGap(59, 59, 59))
        );
        panelA1Layout.setVerticalGroup(
            panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelA1Layout.createSequentialGroup()
                .addComponent(labelDepositoB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labBAñadir)
                        .addComponent(labBQuitar))
                    .addComponent(labBUso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelA1Layout.createSequentialGroup()
                        .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerBAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labBCantidad)
                            .addComponent(spinnerBQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botBAñadir)
                            .addComponent(botBQuitar)
                            .addComponent(labelBAcción))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelA1Layout.createSequentialGroup()
                        .addComponent(labelBCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        panelA2.setBackground(new java.awt.Color(153, 153, 153));

        labCCantidad.setText("Cantidad");

        botCAñadir.setText("Añadir");
        botCAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCAñadirActionPerformed(evt);
            }
        });

        botCQuitar.setText("Quitar");
        botCQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCQuitarActionPerformed(evt);
            }
        });

        spinnerCAñadir.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        labelCAcción.setText("Acción");

        spinnerCQuitar.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        labelDepositoC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDepositoC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDepositoC.setText("DEPÓSITO-C");

        labCAñadir.setText("AÑADIR");

        labCQuitar.setText("QUITAR");

        labelCCapacidad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelCCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCCapacidad.setText(depoC.toString());

        labCUso.setText("AGUA/CAPACIDAD");

        javax.swing.GroupLayout panelA2Layout = new javax.swing.GroupLayout(panelA2);
        panelA2.setLayout(panelA2Layout);
        panelA2Layout.setHorizontalGroup(
            panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDepositoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelA2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labCCantidad)
                    .addComponent(labelCAcción))
                .addGap(18, 18, 18)
                .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botCAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerCAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botCQuitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerCQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelCCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelA2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(labCAñadir)
                .addGap(52, 52, 52)
                .addComponent(labCQuitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(labCUso)
                .addGap(59, 59, 59))
        );
        panelA2Layout.setVerticalGroup(
            panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelA2Layout.createSequentialGroup()
                .addComponent(labelDepositoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labCAñadir)
                        .addComponent(labCQuitar))
                    .addComponent(labCUso, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelA2Layout.createSequentialGroup()
                        .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerCAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCCantidad)
                            .addComponent(spinnerCQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botCAñadir)
                            .addComponent(botCQuitar)
                            .addComponent(labelCAcción))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelA2Layout.createSequentialGroup()
                        .addComponent(labelCCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout SistemaPanelLayout = new javax.swing.GroupLayout(SistemaPanel);
        SistemaPanel.setLayout(SistemaPanelLayout);
        SistemaPanelLayout.setHorizontalGroup(
            SistemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SistemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SistemaPanelLayout.setVerticalGroup(
            SistemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemaPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SistemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(SistemaPanelLayout.createSequentialGroup()
                        .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelA1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelA2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SistemaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SistemaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botCQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCQuitarActionPerformed
        int value = (int) spinnerCQuitar.getValue();
        depoC.quitarAgua(value);
        spinnerCQuitar.setValue(((SpinnerNumberModel) spinnerCQuitar.getModel()).getMinimum());
        labelCCapacidad.setText(depoC.toString());
    }//GEN-LAST:event_botCQuitarActionPerformed

    private void botCAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCAñadirActionPerformed
        int value = (int) spinnerCAñadir.getValue();
        depoC.añadirAgua(value);
        spinnerCAñadir.setValue(((SpinnerNumberModel) spinnerCAñadir.getModel()).getMinimum());
        labelCCapacidad.setText(depoC.toString());
    }//GEN-LAST:event_botCAñadirActionPerformed

    private void botBQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBQuitarActionPerformed
        int value = (int) spinnerBQuitar.getValue();
        depoB.quitarAgua(value);
        spinnerBQuitar.setValue(((SpinnerNumberModel) spinnerBQuitar.getModel()).getMinimum());
        labelBCapacidad.setText(depoB.toString());
    }//GEN-LAST:event_botBQuitarActionPerformed

    private void botBAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBAñadirActionPerformed
        int value = (int) spinnerBAñadir.getValue();
        depoB.añadirAgua(value);
        spinnerBAñadir.setValue(((SpinnerNumberModel) spinnerBAñadir.getModel()).getMinimum());
        labelBCapacidad.setText(depoB.toString());
    }//GEN-LAST:event_botBAñadirActionPerformed

    private void botAQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAQuitarActionPerformed
        int value = (int) spinnerAQuitar.getValue();
        depoA.quitarAgua(value);
        spinnerAQuitar.setValue(((SpinnerNumberModel) spinnerAQuitar.getModel()).getMinimum());
        labelACapacidad.setText(depoA.toString());
    }//GEN-LAST:event_botAQuitarActionPerformed

    private void botAAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAAñadirActionPerformed
        int value = (int) spinnerAAñadir.getValue();
        depoA.añadirAgua(value);
        spinnerAAñadir.setValue(((SpinnerNumberModel) spinnerAAñadir.getModel()).getMinimum());
        labelACapacidad.setText(depoA.toString());
    }//GEN-LAST:event_botAAñadirActionPerformed

    private void butTras70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTras70ActionPerformed
        aguaTraspaso = 70;
        labelTest.setText("Se van a mandar " + aguaTraspaso + "L.");
    }//GEN-LAST:event_butTras70ActionPerformed

    private void butTras40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTras40ActionPerformed
        aguaTraspaso = 40;
        labelTest.setText("Se van a mandar " + aguaTraspaso + "L.");
    }//GEN-LAST:event_butTras40ActionPerformed

    private void butTras25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTras25ActionPerformed
        aguaTraspaso = 25;
        labelTest.setText("Se van a mandar " + aguaTraspaso + "L.");
    }//GEN-LAST:event_butTras25ActionPerformed

    private void butTrasConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTrasConfirmarActionPerformed

        Deposito emisor = (Deposito) comboTrasEmisor.getSelectedItem();
        Deposito receptor = (Deposito) comboTrasReceptor.getSelectedItem();
        sistema.traspasarAgua(emisor, aguaTraspaso, receptor);

        // Esta no es la solución más elegante, pero funciona.
        labelACapacidad.setText(depoA.toString());
        labelBCapacidad.setText(depoB.toString());
        labelCCapacidad.setText(depoC.toString());

    }//GEN-LAST:event_butTrasConfirmarActionPerformed

    private void comboTrasEmisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTrasEmisorActionPerformed
        comboTrasEmisor.setSelectedItem(this);
    }//GEN-LAST:event_comboTrasEmisorActionPerformed

    private void comboTrasReceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTrasReceptorActionPerformed
        comboTrasReceptor.setSelectedItem(this);
    }//GEN-LAST:event_comboTrasReceptorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaDepositosAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaDepositosAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaDepositosAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaDepositosAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaDepositosAgua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SistemaPanel;
    private javax.swing.JButton botAAñadir;
    private javax.swing.JButton botAQuitar;
    private javax.swing.JButton botBAñadir;
    private javax.swing.JButton botBQuitar;
    private javax.swing.JButton botCAñadir;
    private javax.swing.JButton botCQuitar;
    private javax.swing.JButton butTras25;
    private javax.swing.JButton butTras40;
    private javax.swing.JButton butTras70;
    private javax.swing.JButton butTrasConfirmar;
    /*
    private javax.swing.JComboBox<String> comboTrasEmisor;
    */
    private javax.swing.JComboBox<Deposito> comboTrasEmisor;
    /*
    private javax.swing.JComboBox<String> comboTrasReceptor;
    */
    private javax.swing.JComboBox<Deposito> comboTrasReceptor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labAAñadir;
    private javax.swing.JLabel labACantidad;
    private javax.swing.JLabel labAQuitar;
    private javax.swing.JLabel labAUso;
    private javax.swing.JLabel labBAñadir;
    private javax.swing.JLabel labBCantidad;
    private javax.swing.JLabel labBQuitar;
    private javax.swing.JLabel labBUso;
    private javax.swing.JLabel labCAñadir;
    private javax.swing.JLabel labCCantidad;
    private javax.swing.JLabel labCQuitar;
    private javax.swing.JLabel labCUso;
    private javax.swing.JLabel labelAAcción;
    private javax.swing.JLabel labelACapacidad;
    private javax.swing.JLabel labelBAcción;
    private javax.swing.JLabel labelBCapacidad;
    private javax.swing.JLabel labelCAcción;
    private javax.swing.JLabel labelCCapacidad;
    private javax.swing.JLabel labelDepositoA;
    private javax.swing.JLabel labelDepositoB;
    private javax.swing.JLabel labelDepositoC;
    private java.awt.Label labelTest;
    private javax.swing.JLabel labelTrasCantidad;
    private javax.swing.JLabel labelTrasEmisor;
    private javax.swing.JLabel labelTrasReceptor;
    private javax.swing.JLabel labelTraspasar;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelA1;
    private javax.swing.JPanel panelA2;
    private javax.swing.JSpinner spinnerAAñadir;
    private javax.swing.JSpinner spinnerAQuitar;
    private javax.swing.JSpinner spinnerBAñadir;
    private javax.swing.JSpinner spinnerBQuitar;
    private javax.swing.JSpinner spinnerCAñadir;
    private javax.swing.JSpinner spinnerCQuitar;
    // End of variables declaration//GEN-END:variables
}
